spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://sqlvhnegrisoli.ddns.net:5432/ms-venda
    #    jdbc-url: jdbc:postgresql://localhost:5432/ms-venda
    username: postgres
    password: 1y5h8j
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

app-config:
  oauth-clients:
    usuario-api:
      client: usuario-api-client
      secret: usuario-api-secret
    produto-api:
      client: produto-api-client
      secret: produto-api-secret
    venda-api:
      client: venda-api-client
      secret: venda-api-secret

  services:
    usuario-api:
      url: http://localhost:8080
    produto-api:
      url: http://localhost:8081
    venda-api:
      url: http://localhost:8082

security:
  oauth2:
    resource:
      filter-order: 3

server:
  port: 8082

